name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - Documentation        # or 'Documentation' while testing

permissions:
  contents: write   # needed to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material pymdown-extensions

      - name: Deploy with MkDocs
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

